### ISSUE TITLE
acertmgr will not download all required intermediate certificates

### ISSUE THREAD

**Issue by moepman** [moepman/acertmgr#53]
It seems as per https://github.com/moepman/acertmgr/blob/ce157a5c8afbcc42146a353845d23f731fb56699/acertmgr/authority/v2.py#L264 we accept two CERTIFICATE blocks (one as cert, one as CA) - however as described in the RFC https://datatracker.ietf.org/doc/html/rfc8555#section-7.4.2 there can be multiple entries in the chain and this leads to problems with the new default chain for Let's Encrypt.

As can be seen at https://letsencrypt.org/2020/12/21/extending-android-compatibility.html we need to fetch R3 and X1 for a full chain that also works on older devices, but we only seem to fetch R3.

**Comment by davidklaftenegger** [comment]
The current behaviour only "mostly works" because R3 is signed by the self-signed X1, which happens to be trusted by newer devices. This effectively, but unintentionally, uses the (blue) alternative chain.

**Comment by Kishi85** [comment]
This is happening due to the way we handle the CA and certificates in all other parts of the code, which is as a single cryptography certificate object (thats the main reason there is only a single ca certificate supported so far, keeping compatibility with older parts of the code) and not simply a string. I'll check the code for a better way to do this, maybe we should just move to PEM-strings within the rest of processing and do the conversion right were it is needed? Most of the time PEM would be used anyway so it might simplyfy a few things ?

**Comment by Kishi85** [comment]
PR#54 should fix the issue in a rather simple and easy way. Please review and test.

**Comment by moepman** [comment]
So according to tests done by @Kishi85 the change in #54 alone will not lead to a correct certificate chain, because LE doesn't supply the full chain in the first place.
Maybe we need to look at the RFC again and see if there is an option we need to set.

**Comment by Kishi85** [comment]
From what i can gather it should work once Let's Encrypt pushes their full chain through. We already use only defaults and have done so since this was changed for the X3->R3 transition. The only missing thing is the full processing of the CA chain, which is added in PR #54.

**Comment by davidklaftenegger** [comment]
I don't think letsencrypt plans any changes on their end. A test yesterday with certbot has shown that those users end up with the intermediate chain available, so providing this functionality probably falls on ACME clients.

**Comment by Kishi85** [comment]
Lets Encyrpt was providing the data fully. There was just a problem with the chain parsing on my end. I've fixed and updated the PR.
